site_name: Sportradar API Wrapper

theme:
    name: material

plugins:
  - search
  - mkdocstrings
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: timeago
  - git-authors:
      show_contribution: True

nav:
  - index.md
  - SoccerExtended.md
