site_name: Sportradar API
repo_url: https://github.com/felipeall/sportradar-api/
repo_name: sportradar-api

theme:
    name: material

plugins:
  - search
  - mkdocstrings
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: timeago
  - git-authors:
      show_contribution: True

nav:
  - index.md
  - SoccerExtended.md
